networks:
  iuniket:
    driver: bridge
    name: iuniket

volumes:
  database-data:
    driver: local

services:
  database:
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./db/project.sql:/docker-entrypoint-initdb.d/init.sql
    mem_limit: 1g               # Limita a memória física a 1GB
    memswap_limit: 1g           # Define o total de memória + swap para 1gB
    networks:
      - iuniket

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    mem_limit: 1g               # Limita a memória física a 1GB
    memswap_limit: 1g           # Define o total de memória + swap para 1gB
    depends_on:
      - database
    networks:
      - iuniket

  backend:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${API_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_PASS: ${JWT_PASS}
      FROM_MAIL: ${FROM_MAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    mem_limit: 1g               # Limita a memória física a 1GB
    memswap_limit: 1g           # Define o total de memória + swap para 1gB
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - database
    networks:
      - iuniket

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    mem_limit: 1g               # Limita a memória física a 1GB
    memswap_limit: 1g           # Define o total de memória + swap para 1gB
    depends_on:
      - backend
    networks:
      - iuniket

  proxy:
    image: nginx:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - iuniket
